sw_application_homepage:
    pattern:  /
    defaults: { _controller: SwApplicationBundle:Default:index }

sw_application_swimmingpools_list:
    pattern:  /swimming-pool/
    defaults: { _controller: SwApplicationBundle:Default:getSwimmingPools }
    requirements:
        _method:  GET
        _format:  json

sw_application_swimmingpools_add_comment:
    pattern:  /swimming-pool/{swimmingPoolId}/add
    defaults: { _controller: SwApplicationBundle:SoapClient:addComment, swimmingPoolId : 1 }
    #condition: "request.headers.get('X-Requested-With') == 'XmlHttpRequest'"

sw_application_swimmingpools_get_comment:
    pattern:  /swimming-pool/{swimmingPoolId}/comment
    defaults: { _controller: SwApplicationBundle:SoapClient:getComments, swimmingPoolId : 1 }
    #condition: "request.headers.get('X-Requested-With') == 'XmlHttpRequest'"

sw_application_swimmingpools_goodbye:
    pattern:  /swimming-pool/goodbye/{name}
    defaults: { _controller: SwApplicationBundle:SoapClient:goodBye, name : "symfony" }
    #condition: "request.headers.get('X-Requested-With') == 'XmlHttpRequest'"
