sw_application:
    resource: "@SwApplicationBundle/Resources/config/routing.yml"
    prefix:   /

_besimple_soap:
    resource: "@BeSimpleSoapBundle/Resources/config/routing/webservicecontroller.xml"
    prefix:   /ws
