sw_application:
    resource: "@SwApplicationBundle/Resources/config/routing.yml"
    prefix:   /

sw_soap_comment:
    resource: "@SwSoapCommentBundle/Resources/config/routing.yml"
    prefix:   /soap/

sw_rest_swimming:
    resource: "@SwRestSwimmingBundle/Resources/config/routing.yml"
    prefix:   /swimming/

_besimple_soap:
    resource: "@BeSimpleSoapBundle/Resources/config/routing/webservicecontroller.xml"
    prefix:   /ws

